### ISSUE TITLE
imports are not considered when used in the fragment/block

### ISSUE THREAD

**Issue by scratchmex** [sponsfreixes/jinja2-fragments#24] opened 2023-12-30 19:39 UTC
If I am using macros (used as components) inside a block I want to render

```
render_block(templates.env, "index.html.j2", "tracks_body", **context)
```

 it fails like this:

```
  File "templates/index.html.j2", line 72, in block 'tracks_body'
    {{ m.spotify_link(href=track.external_urls['spotify']) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xyz/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'm' is undefined
```

when in `index.html.j2` I have

```
{% import "_macros.j2" as m %}

...

{% block tracks_body %}
...
{{ m.spotify_link(href=track.external_urls['spotify']) }}
...
{% endblock %}
```

Can we have some type of heuristic that when an import is used then we pass that to the context as well?

**Comment by sponsfreixes** [comment] 2024-01-22 01:51
Duplicate of #21.

**Closed by sponsfreixes** 2024-01-22 01:51 UTC
Labels: enhancement
